---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: registry.spritsail.io/spritsail/docker-build

- name: publish-spritsail
  pull: always
  image: registry.spritsail.io/spritsail/docker-publish
  settings:
    registry: registry.spritsail.io
    login: {from_secret: spritsail_login}
    repo: spritsail/fivem
    tags:
    - latest
    - "%label org.label-schema.version"
    delete: no  # so we can push to dockerhub+ghcr
  when:
    branch:
    - master
    event:
    - push

- name: publish-ghcr
  pull: never
  image: registry.spritsail.io/spritsail/docker-publish
  settings:
    registry: ghcr.io
    login: {from_secret: ghcr_login}
    repo: spritsail/fivem
    tags:
    - latest
    - "%label org.label-schema.version"
    delete: no  # so we can push to dockerhub
  when:
    branch:
    - master
    event:
    - push

- name: publish-dockerhub
  pull: never
  image: registry.spritsail.io/spritsail/docker-publish
  settings:
    login: {from_secret: docker_login}
    repo: spritsail/fivem
    tags:
    - latest
    - "%label org.label-schema.version"
  when:
    branch:
    - master
    event:
    - push

---
kind: pipeline
name: update-readme

steps:
- name: dockerhub-readme
  pull: always
  image: jlesage/drone-push-readme
  settings:
    username: {from_secret: docker_username}
    password: {from_secret: docker_password}
    repo: spritsail/fivem
  when:
    branch:
    - master
    event:
    - push

---
kind: signature
hmac: 5a4a990e8643c2c9a3782f13e509469be27c7fdb517672697bd3e6e7234fc8dc

...
