version: '3'

services:
  fivem:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-fivem-fexemu
    container_name: fivem
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - "fivem:/config"
      # Enable a volume mount for txAdmin's data files
      # - "txdata:/txData"
    ports:
      - "30120:30120"
      - "30120:30120/udp"
      # Allow txAdmin's webserver port to be accessible
      # - "40120:40120"
    environment:
      LICENSE_KEY: "license-key-here"

volumes:
  fivem:
#  txdata: