name: Build for Test Docker Image

on:
#  schedule:
#    - cron: '44 14 */3 * 2'
  push:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  test_amd64_arm64:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read

    steps:
      - name: Checkout Dockerfile
        id: checkout
        uses: actions/checkout@v5

      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          flavor: |
            latest=${{ startsWith(github.ref, 'refs/heads/master') }}

      - name: Build main Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          build-args: GH_TOKEN=${{ github.token }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-to: type=gha,mode=max,ignore-error=true
          cache-from: type=gha
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
